# nfl_teams_divisions.py

nfl_teams = {
    "Falcons": "NFC South",
    "Ravens": "AFC North",
    "Bills": "AFC East",
    "Bengals": "AFC North",
    "Cowboys": "NFC East",
    "Broncos": "AFC West",
    "Lions": "NFC North",
    "Packers": "NFC North",
    "Texans": "AFC South",
    "Colts": "AFC South",
    "Chiefs": "AFC West",
    "Rams": "NFC West",
    "Dolphins": "AFC East",
    "Vikings": "NFC North",
    "Jets": "AFC East",
    "Eagles": "NFC East",
    "Steelers": "AFC North",
    "49ers": "NFC West",
    "Seahawks": "NFC West",
    "Buccaneers": "NFC South",
    "Titans": "AFC South",
    "Commanders": "NFC East",
    "Giants": "NFC East",
    "Bears": "NFC North",
    "Panthers": "NFC South",
    "Saints": "NFC South",
    "Cardinals": "NFC West",
    "Patriots": "AFC East",
    "Browns": "AFC North",
    "Jaguars": "AFC South",
    "Raiders": "AFC West",
    "Chargers": "AFC West"
}
